### ISSUE TITLE
Add copy button error: 

### ISSUE THREAD

**Issue by CodingCattwo** [choldgraf/sphinx-copybutton#55]
Stacktrace: 
```
Running Sphinx v1.6.7
...

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/webase-doc-cattwo/envs/latest/lib/python3.7/site-packages/sphinx/cmdline.py", line 305, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/webase-doc-cattwo/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 196, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/webase-doc-cattwo/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 456, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/webase-doc-cattwo/envs/latest/lib/python3.7/site-packages/sphinx/registry.py", line 207, in load_extension
    metadata = mod.setup(app)
  File "/home/docs/checkouts/readthedocs.org/user_builds/webase-doc-cattwo/envs/latest/lib/python3.7/site-packages/sphinx_copybutton/__init__.py", line 25, in setup
    app.add_js_file('clipboard.min.js')
AttributeError: 'Sphinx' object has no attribute 'add_js_file'

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/webase-doc-cattwo/envs/latest/lib/python3.7/site-packages/sphinx_copybutton/__init__.py", line 25, in setup
    app.add_js_file('clipboard.min.js')
AttributeError: 'Sphinx' object has no attribute 'add_js_file'
```

My doc project is [WeBASE-Doc](https://github.com/WeBankFinTech/WeBASE-Doc)

**Comment by choldgraf** [comment]
@CodingCattwo can you upgrade sphinx and see if that fixes it?
